### PR TITLE
Update kaios

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by seinlin** [comment]
FYI, I have some fix in system/sepolicy, so we can continue using gonk_android-10.0.0_r11.

**Comment by seinlin** [comment]
The other patch had been merged at https://github.com/kaiostech/manifests/commit/a605ab4265e90d4d506517c22404abf5284cc812

**Comment by lissyx** [comment]
> FYI, I have some fix in system/sepolicy, so we can continue using gonk_android-10.0.0_r11.

Currently it completely breaks emulator and device builds, so if you have fixes for that its good.

**Comment by seinlin** [comment]
> 
> Currently it completely breaks emulator and device builds, so if you have fixes for that its good.
Yep, I verified the emulator build, it is good now.

**Pull request closed without merging**
