### PR TITLE
To add gonk-binder repo. r=seinlin.

### PR DESCRIPTION
**Pull request by jackdesu**
Hi @seinlin 
  can you help this PR?
  thanks.

### CODE REVIEW

**Comment by lissyx** [comment]
@jackdesu Could you please make the binder repo you are adding public ? We are struggling to build current Gecko because it is still private. Thanks!

**Comment by fabricedesre** [comment]
@lissyx please check now that https://github.com/kaiostech/gonk-binder is public. Thanks!

**Comment by lissyx** [comment]
> @lissyx please check now that https://github.com/kaiostech/gonk-binder is public. Thanks!

Indeed, thanks!

**Comment by seinlin** [comment]
> @lissyx please check now that https://github.com/kaiostech/gonk-binder is public. Thanks!

Thanks!

**Pull request merged**
